# states.py
CHOOSING_LANGUAGE = 0
CHOOSING_SALON = 1
CHOOSING_BARBERS = 2
CHOOSING_SERVICES = 3
CHOOSING_DATE = 4
CHOOSING_HOUR = 5
CHOOSING_MINUTES = 6
CHOOSING_OPTION = 7 
CONFIRM_BOOKING = 8
ASK_TG_PHONE = 9